In [1]:
import pandas as pd

In [3]:
dataframe = pd.read_csv('https://www.football-data.co.uk/mmz4281/2425/E0.csv')

In [5]:
dataframe

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,E0,26/02/2025,19:30,Man United,Ipswich,3,2,H,2,2,...,1.83,2.10,1.87,2.10,1.90,2.12,1.83,2.05,1.88,2.12
267,E0,26/02/2025,19:30,Nott'm Forest,Arsenal,0,0,D,0,0,...,1.95,1.98,1.95,1.97,1.98,1.98,1.92,1.94,2.00,1.99
268,E0,26/02/2025,19:30,Tottenham,Man City,0,1,A,0,1,...,2.03,1.78,2.07,1.86,2.11,1.86,2.04,1.82,2.12,1.89
269,E0,26/02/2025,20:15,Liverpool,Newcastle,2,0,H,1,0,...,2.02,1.91,2.02,1.90,2.04,1.95,1.98,1.88,2.06,1.92
270,E0,27/02/2025,20:00,West Ham,Leicester,2,0,H,2,0,...,2.05,1.88,2.03,1.89,2.07,2.00,1.98,1.89,2.07,1.91

In [7]:
dataframe.rename(columns= {'FTHG':"king",
                           'FTAG':'queen'},inplace= True)

In [8]:
dataframe

,Div,Date,Time,HomeTeam,AwayTeam,king,queen,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,E0,26/02/2025,19:30,Man United,Ipswich,3,2,H,2,2,...,1.83,2.10,1.87,2.10,1.90,2.12,1.83,2.05,1.88,2.12
267,E0,26/02/2025,19:30,Nott'm Forest,Arsenal,0,0,D,0,0,...,1.95,1.98,1.95,1.97,1.98,1.98,1.92,1.94,2.00,1.99
268,E0,26/02/2025,19:30,Tottenham,Man City,0,1,A,0,1,...,2.03,1.78,2.07,1.86,2.11,1.86,2.04,1.82,2.12,1.89
269,E0,26/02/2025,20:15,Liverpool,Newcastle,2,0,H,1,0,...,2.02,1.91,2.02,1.90,2.04,1.95,1.98,1.88,2.06,1.92
270,E0,27/02/2025,20:00,West Ham,Leicester,2,0,H,2,0,...,2.05,1.88,2.03,1.89,2.07,2.00,1.98,1.89,2.07,1.91